services:
    redis:
        image: 'redis:alpine'
        restart: always
        container_name: redis
        ports: 
            - 6379:6379
        volumes:
            - 'redis-data:/data'
        networks:
            - share_network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

volumes:
    redis-data:
        driver: local
networks:
   share_network:
     external: true
